# Generated by Django 4.2 on 2026-02-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_admission', models.CharField(max_length=50)),
                ('fee_total', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('library_fine', models.IntegerField(default=0)),
                ('equipment_fine', models.IntegerField(default=0)),
                ('paid_crt_fee', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_info', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('mid_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=50)),
                ('mid_marks', models.IntegerField()),
                ('quiz_marks', models.IntegerField()),
                ('assignment_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_data', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'semester_id', 'mid_id', 'course_id')},
            },
        ),
    ]
