# Generated by Django 4.2 on 2026-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementemployee',
            name='passcode',
            field=models.CharField(max_length=255),
        ),
    ]
