# Generated by Django 4.2 on 2026-02-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=50)),
                ('class_records', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'semester_id', 'course_id')},
            },
        ),
    ]
