# Generated by Django 4.2 on 2026-02-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('year_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('sec_id', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=15)),
                ('ssc_marks', models.FloatField(blank=True, null=True)),
                ('inter_marks', models.FloatField(blank=True, null=True)),
                ('passcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'semester_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=50)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('attendance', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'semester_id', 'course_code')},
            },
        ),
    ]
