# Generated by Django 4.2 on 2026-02-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentfee_studentexamdata'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=50)),
                ('assignment_pdf', models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marks_awarded', models.IntegerField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='faculty.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student', '-submitted_at'], name='assignments_student_0d51ed_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['faculty', '-submitted_at'], name='assignments_faculty_20a694_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course_id'], name='assignments_course__91e566_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['marks_awarded'], name='assignments_marks_a_8279cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student', 'faculty', 'course_id')},
        ),
    ]
