# Generated by Django 4.2 on 2026-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TPCellEmployee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passcode', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
